# Generated by Django 4.2.6 on 2024-04-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='positions',
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff.position'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='subposition',
        ),
        migrations.AddField(
            model_name='staff',
            name='subposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff.subposition'),
        ),
    ]
