# Generated by Django 4.2.6 on 2024-04-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_remove_staff_positions_staff_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='subposition',
        ),
        migrations.AddField(
            model_name='staff',
            name='subpositions',
            field=models.ManyToManyField(null=True, to='Staff.subposition'),
        ),
    ]
