# Generated by Django 4.2.6 on 2024-04-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_remove_staff_position_remove_staff_subposition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='subpositions',
            new_name='subposition',
        ),
    ]
