# Generated by Django 4.2.6 on 2024-04-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_rename_subpositions_staff_subposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
