# Generated by Django 4.2.6 on 2024-04-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0005_alter_staff_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('FOH', 'FOH'), ('BOH', 'BOH'), ('Manager', 'Manager')], max_length=100),
        ),
    ]
