# Generated by Django 5.0.4 on 2024-04-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlateMate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerID', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderTime', models.DateTimeField()),
                ('MenuItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlateMate.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('OrderTime', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('MenuItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlateMate.menuitem')),
                ('TableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlateMate.table')),
            ],
        ),
    ]
