# Generated by Django 4.2.6 on 2024-04-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlateMate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('shape', models.CharField(choices=[('circle', 'Circle'), ('rectangle', 'Rectangle'), ('square', 'Square')], max_length=10)),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('table_number', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='PlateMate.floorplan')),
            ],
        ),
    ]
