# Generated by Django 5.0.3 on 2024-04-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlateMate', '0002_table_orderinghistory_activeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeorder',
            name='Ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activeorder',
            name='MenuItemID',
            field=models.IntegerField(),
        ),
    ]
