# Generated by Django 4.2.6 on 2024-04-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlateMate', '0002_floorplan_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_boxes', to='PlateMate.floorplan')),
            ],
        ),
    ]
