# Generated by Django 4.2.6 on 2024-04-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlateMate', '0003_textbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbox',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
    ]
