# Generated by Django 4.2.6 on 2024-04-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlateMate', '0004_textbox_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbox',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
