# Generated by Django 4.2.6 on 2024-04-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlateMate', '0005_alter_textbox_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='isOccupiedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OrderingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderTime', models.DateTimeField()),
                ('MenuItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlateMate.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuItemID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('OrderTime', models.DateTimeField(auto_now_add=True)),
                ('Ordered', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('TableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlateMate.table')),
            ],
        ),
    ]
