# Generated by Django 4.2.6 on 2024-04-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlateMate', '0005_alter_textbox_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='isOccupiedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
